### ISSUE TITLE
Is the snippet provided in the Nix + flakes documentation incorrect?

### ISSUE THREAD

**Issue by bzm3r** [anyrun-org/anyrun#109]
A link to the section I am referring to: https://github.com/Kirottu/anyrun?tab=readme-ov-file#nix

In particular, in this snippet:

```rust
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    anyrun.url = "github:Kirottu/anyrun";
    anyrun.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, anyrun }: let
  in {
    nixosConfigurations.HOSTNAME = nixpkgs.lib.nixosSystem {
      # ...

      system.packages = [ anyrun.packages.${system}.anyrun ];

      # ...
    };
  };
}
```

...is the line `system.packages = [...]` supposed to be `environment.systemPackages = [...]`?

**Comment by NotAShelf** [comment]
that's correct, it should be environment.systemPackages and not system.packages

**Comment by NotAShelf** [comment]
#138 does not address the issue. As I've said, it should be `environment.systemPackages`.
