### ISSUE TITLE
Customize icon size

### ISSUE THREAD

**Issue by steakscience** [anyrun-org/anyrun#137]
I tried tinkering around with GTK CSS but couldn't find a way to change the icon size.

Does anyone know whether this is possible?

Thanks

**Comment by Alexdelia** [comment]
after struggling for a few hours, the only way I found to work is:
```css
image {
  -gtk-icon-transform: scale(2.0);
}
```

sadly it makes the icon quite pixelated

this might be related to the hardcoded:
https://github.com/anyrun-org/anyrun/blob/b3b4f2253d43af3311b3d3fc86973fc3e9559c33/anyrun/src/main.rs#L839

also, this doesn't change the box size of the icon

here is the `commit` that change this in my setup
https://github.com/Alexdelia/nixconf/commit/e78a7d33306aa037665e26bf4f725f50280d4f73

**Comment by steakscience** [comment]
@Alexdelia Thank you so much
