### ISSUE TITLE
Transparency does not work

### ISSUE THREAD

**Issue by 0thElement** [anyrun-org/anyrun#168]
I'm currently using Hyprland. I can not get anyrun's background to be transparent. With the default styling, and even with the following css it does not seem to apply.

```cs
#window,
#match,
#entry,
#plugin,
#main { 
  background: transparent; 
}
```

![image](https://github.com/anyrun-org/anyrun/assets/71188597/41df6d9b-012d-4238-b785-cbf3b2f121ac)

I'm not sure if this is an issue with anyrun specifically or my hyprland config is wrong. But I'd appreciate if anyone else can help me out.

**Comment by 00-kat** [comment]
> I'm currently using Hyprland.

Layers don't get blurred by default, did you forget to add
```
layerrule = blur, (anyrun)
```
to your Hyprland config?

(Note: if that makes rounded borders look weird, try also adding this:
```
layerrule = ignorezero, (anyrun)
```
)
