### ISSUE TITLE
Community Platform (Chat/Forum)

### ISSUE THREAD

**Issue by Sntx626** [anyrun-org/anyrun#177]
I think we should set up a platform for people to chat, so that we don't have to rely on issues for smaller communication.

My current suggestions would be either:

- Matrix
- Discord

Further suggestions are welcome, however I think the final say should be with @Kirottu

**Comment by abenz1267** [comment]
Check https://github.com/anyrun-org/anyrun/issues/158#issuecomment-2132710775

**Comment by Sntx626** [comment]
> Check [#158 (comment)](https://github.com/anyrun-org/anyrun/issues/158#issuecomment-2132710775)

Ok, in this case I'll close this issue - since there's no reason to build a community.
