### ISSUE TITLE
New desktop entires wont show up on results

### ISSUE THREAD

**Issue by iUnstable0** [anyrun-org/anyrun#185]
Hi

This is my anyrun config file

```
Config(
  x: Fraction(0.500000),
  y: Absolute(15),
  width: Fraction(0.300000),
  height: Absolute(0),
  hide_icons: false,
  ignore_exclusive_zones: false,
  layer: Overlay,
  hide_plugin_info: true,
  close_on_click: true,
  show_results_immediately: false,
  max_entries: None,
)
```

Im on Arch and i installed anyrun from the AUR
whenever i install a new app, it wont show up on anyrun results unless i restart anyrun process.
like its not reloading everytime a new desktop entry is created in /usr/share/applications?

**Comment by Kirottu** [comment]
Anyrun only scrubs for desktop files on launch, not continuously. Is there a reason why you would need new desktop entries to show up on an already running instance?

**Comment by iUnstable0** [comment]
because when new programs are isntalled while anyrunb is running it wont show up on the results

**Comment by abenz1267** [comment]
Anyrun is not designed to be a long-running process, so your use-case here doesn't really make sense. How do you even keep the instance running? Anyrun is not designed for that.

**Comment by iUnstable0** [comment]
Ohhhh i see now, sorry
Im using this https://github.com/end-4/dots-hyprland dotfiles and its using anyrun for app launching, idk how they do it too.

**Comment by yvvki** [comment]
What are you trying to do? Running Anyrun in advance to run an application that is still installing seems counterproductive.
