### ISSUE TITLE
home-manager module fails build on certain systems

### ISSUE THREAD

**Issue by Sntx626** [anyrun-org/anyrun#81]
From what I can see [these two lines](https://github.com/Kirottu/anyrun/blob/master/nix/hm-module.nix#L210-L212) make assumptions about configuration that is not present on all systems.

If that's the case, the error `'config.xdg.configFile' is undefined` is thrown.

I fixed it by forking this repo and changing [this](https://git.sr.ht/~sntx/anyrun/commit/d0aae8cdf4efd658737099f7609c13fd24932baf#nix/hm-module.nix) line.

However that only works if something like the following is defined somewhere else in the config:

```nix
{ config, options, lib, ... }:

with lib;

{
  options = {
    home = {
      programs = mkOption {};
      xdg = mkOption {};
    };
  };
  config = {
    home-manager.users."alice" = {
      programs = mkAliasDefinitions options.home.programs;
      xdg = mkAliasDefinitions options.home.xdg;
    };
  };
}
```

**Comment by Kirottu** [comment]
Can you take a look at this @NotAShelf?

**Comment by NotAShelf** [comment]
you're right
looks like both I and n3oney missed that, could you make a PR?

**Comment by Sntx626** [comment]
I'm currently working on an example restructure for the repo (c.f. #87).
I'll look into it once I've finished that.

**Comment by eyduh** [comment]
the link to the fix is dead, is there a commit/branch on this git?

**Comment by Sntx626** [comment]
The fix to this is to import the `anyrun.homeManagerModules.anyrun` from within your hm configuration, not your nixos configuration.

[This](https://git.sr.ht/~sntx/hive/tree/db15531fa1e9e21ca543318f5a160edfca11670e/item/cells/hive/homeProfiles/anyrun/default.nix) is the current config I'm using for the anyrun module:

```nix
{
  inputs,
  lib,
  pkgs,
}:
let
  inherit (inputs) anyrun;
in
{
  imports = [ anyrun.homeManagerModules.anyrun ];

  programs.anyrun = {
    enable = true;
    config = {
      plugins = with anyrun.packages.${pkgs.system}; [
        applications
        dictionary
        rink
        symbols
        translate
      ];
      x = {
        fraction = 0.5;
      };
      y = {
        fraction = 0.3;
      };
    };
    extraConfigFiles."applications.ron".text = ''
      Config(
        desktop_actions: false,
        max_entries: 8,
        terminal: Some("foot"),
      )
    '';
    extraCss = builtins.readFile ./__style.css;
  };
}
```

Here's an example on how to use it.

```nix
{ inputs, ... }: {
  # These are the nixos imports
  imports = [
    inputs.home-manager.nixosModules.home-manager
  ];
  
  home-manager.users.sntx = {
    # These are the hm imports
    imports = [
      inputs.anyrun.homeManagerModules.anyrun
      ./anyrun # <- This would be the config linked above
    ];
  };
}
```
